### ISSUE TITLE
Failed to compile subgraph, Import file not found

### ISSUE THREAD

**Issue by fafrd** [ensdomains/ens-subgraph#23]
Getting an error when trying to build this (so I can deploy it to a local graph node). What am I doing wrong here? I pulled down the repo, did an `npm install`, and then it doesn't seem to build.

Using graph-cli version 0.19.0.

```bash
% graph build
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: ENSRegistry => build/ENSRegistry/ENSRegistry.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: Import file 'src/types/ENSRegistry/EnsRegistry.ts' not found.
Error: Failed to compile data source mapping: Import file 'src/types/ENSRegistry/EnsRegistry.ts' not found.
    at Compiler._compileDataSourceMapping (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:312:13)
    at /Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:206:20
    at updateInDeepMap (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1278:26)
    at /Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/src/compiler.js:205:24
    at /Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/kian/.nvm/versions/node/v14.1.0/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3015:23)
```

**Comment by fafrd** [comment]
Ah- figured it out. I forgot to run `graph codegen`, which creates the .ts files needed here.

Closing out this issue :)

**Comment by parv3213** [comment]
> graph codegen

`npm run codegen`

**Comment by LuckyDogeDev** [comment]
> Ah- figured it out. I forgot to run `graph codegen`, which creates the .ts files needed here.
> 
> Closing out this issue :)

This did not work for me I am still getting this error

`  Compile data source: Factory => build/Factory/Factory.wasm
✖ Failed to compile subgraph: Failed to compile data source mapping: assertion failed
Error: Failed to compile data source mapping: assertion failed
`
